; Límits de memòria i pujada
memory_limit = 256M
upload_max_filesize = 50M
post_max_size = 50M

; Seguretat: Ocultar errors a l'usuari final
display_errors = Off
display_startup_errors = Off
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
expose_php = Off

; Rendiment: Activar OPcache
opcache.enable=1
opcache.memory_consumption=256
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=20000
opcache.validate_timestamps=0