server {
    listen 80;
    server_name _; # Esto acepta cualquier conexión por IP

    # Frontend Next.js
    location / {
        proxy_pass http://client:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Backend Laravel API
    location /api {
        proxy_pass http://api:9000; # O si usas PHP-FPM directamente:
        # try_files $uri $uri/ /index.php?$query_string;
    }

    # WebSockets Node.js
    location /socket.io/ {
        proxy_pass http://socket:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
}